### ISSUE TITLE
SwiftLSPClient does not recover from host process crash

### ISSUE THREAD

**Issue by johnno1962** [ChimeHQ/SwiftLSPClient#39]
Hi @mattmassicotte,

I'm seeing a some strange behaviour if the sourcekit-lsp server process crashes. I get a stack trace:
```
Crashed Thread:        8  Dispatch queue: com.apple.root.user-interactive-qos.overcommit

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
Fatal error: Attempted to read an unowned reference but object 0x7f9c7ad050a0 was already deallocated
abort() called

Thread 8 Crashed:: Dispatch queue: com.apple.root.user-interactive-qos.overcommit
0   libsystem_kernel.dylib        	0x00007fff7199e2c6 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff71a59bf1 pthread_kill + 284
2   libsystem_c.dylib             	0x00007fff719086a6 abort + 127
3   libswiftCore.dylib            	0x00007fff71279ed5 swift::fatalError(unsigned int, char const*, ...) + 149
4   libswiftCore.dylib            	0x00007fff7127a0c5 swift::swift_abortRetainUnowned(void const*) + 53
5   libswiftCore.dylib            	0x00007fff7127b752 swift_unownedRetainStrong + 98
6   com.chimehq.SwiftLSPClient    	0x00000001067470ee closure #1 in LanguageServerProcessHost.init(path:arguments:environment:) + 46 (LanguageServerProcessHost.swift:52)
7   com.chimehq.SwiftLSPClient    	0x00000001067471c6 thunk for @escaping @callee_guaranteed (@guaranteed NSTask) -> () + 70
8   com.apple.Foundation          	0x00007fff47c659b3 __45-[NSConcreteTask launchWithDictionary:error:]_block_invoke_2 + 20
9   libdispatch.dylib             	0x00007fff718155f8 _dispatch_call_block_and_release + 12
10  libdispatch.dylib             	0x00007fff7181663d _dispatch_client_callout + 8
11  libdispatch.dylib             	0x00007fff71824509 _dispatch_root_queue_drain + 657
12  libdispatch.dylib             	0x00007fff71824b46 _dispatch_worker_thread2 + 90
13  libsystem_pthread.dylib       	0x00007fff71a566b3 _pthread_wqthread + 583
14  libsystem_pthread.dylib       	0x00007fff71a563fd start_wqthread + 13
```
The crash is on line 52 of LanguageServerProcessHost.swift in the termination handler.
```
0051          process.terminationHandler = { [unowned self] (task) in
0052              self.transport.close()
0053          }
```
I've filled a PR to fix the underlying problem https://github.com/apple/sourcekit-lsp/pull/198 but if this could be fixed in SwiftLSPClient it would be more evident the host process was the issue. If you want to replicate, run https://github.com/johnno1962/siteify repeatedly using a development toolchain. It will eventually fail though the crash is very rare.

**Comment by mattmassicotte** [comment]
mmmm, interesting. This looks like a life-cycle issue, but it isn't immediately clear to me what the problem is.

I guess somehow the project object is executing this code after `self` is no-longer around? It shouldn't be terribly hard for me to create an artificial crash in a server I use to try to reproduce this.

**Comment by johnno1962** [comment]
This has been fixed in sourcekit-lsp so it’s less of a concern now.

**Comment by mattmassicotte** [comment]
Glad to hear it's fixed, but I think it's totally reasonable to leave this open. Definitely still an issue in this library.
